theme: jekyll-theme-minimal
title: Welcome to Tim Davis' personal web page
description: Tim Davis' personal web page
markdown: kramdown
github:
  is_project_page: false
  is_user_page: true
  owner_name: Tim Davis
  repository_nwo: github.com/drtimothyaldendavis
